apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
    - name: hasura
      env: secret.properties

configMapGenerator:
    - name: hasura
      env: config.properties

resources:
  - hasura.yaml
  - postgis.yaml
